define([
  './alertSrv',
  './datasourceSrv',
  './filterSrv',
  './mapSrv',
  './panelSrv',
  './timer',
  './panelMove',
  './keyboardManager',
  './annotationsSrv',
  './playlistSrv',
  './unsavedChangesSrv',
  './dashboard/dashboardKeyBindings',
  './dashboard/dashboardSrv',
  './dashboard/dashboardViewStateSrv',
],
function () {});
